ProjectsMap.Web/Controllers/SecurityController.cs
using EGIC.Core.Domain.Users;
using EGIC.Core.Models.Security;
using EGIC.Core.Models.Users;
using Microsoft.AspNetCore.Mvc;
using ProjectsMap.Services.Authentication;
using System;

namespace ProjectsMap.Web.Controllers
{
    public class SecurityController : BaseController
    {
        #region Fields

        private readonly IAuthenticationService _authenticationService;

        #endregion

        #region CTOR

        public SecurityController(
            IServiceProvider service,
            IAuthenticationService authenticationService) : base(service)
        {
            _authenticationService = authenticationService;
        }

        #endregion


        #region Actions

        #region Login/Logout

        [Route("/login")]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        [Route("/login")]
        public virtual IActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                model.Username = model.Username.Trim().ToUpper();
                var loginResult = _authenticationService.ValidateUser(model.Username, model.Password, out User user);
                switch (loginResult)
                {
                    case UserLoginResults.Successful:
                        {


                            //sign in new user
                            _authenticationService.SignIn(user);

                            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
                                return RedirectToAction("Index", "Home");

                            return Redirect(returnUrl);
                        }
                    case UserLoginResults.UserNotExist:
                        ModelState.AddModelError("", "User not existed");
                        break;
                    case UserLoginResults.Deleted:
                        ModelState.AddModelError("", "User has been deactivated");
                        break;
                    case UserLoginResults.WrongPassword:
                    default:
                        ModelState.AddModelError("", "Wrong password, please make sure your password and try again.");//
                        break;
                }
            }

            return View(model);
        }

        [Route("/logout")]
        public virtual IActionResult Logout()
        {
            //standard logout 
            _authenticationService.SignOut();

            return RedirectToAction("Login");
        }

        #endregion

        public virtual IActionResult AccessDenied(string pageUrl)
        {
            var currentUser = _workContext.CurrentUser;
            return View();
        }

        #endregion
    }
}

ProjectsMap.Web/Views/Security/AccessDenied.cshtml
<div class="content text-center">
    <div class="content-header">
        <h1>
            Access Denied
        </h1>
    </div>
    <i class="fa fa-minus-circle" style="font-size:260px;color:#e66666;"></i>
    <div class="alert alert-danger alert-dismissable">
        You tried to access unauthorized page.
    </div>
</div>

ProjectsMap.Web/Views/Security/Login.cshtml
@model LoginModel
@using EGIC.Core.Models.Security
@{
    //Layout = "_AdminLayout";
    Layout = null;// "_AdminLayout";
    string pageTitle = "Login";
    //title
    ViewBag.Title = pageTitle;
}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EGIC - Projects Map | Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/adminLTE/AdminLTE-2.3.0.min.css" />

    <!-- Font Awesome -->
    <link href="~/lib/fontAwesome/css/font-awesome-4.6.3.min.css" rel="stylesheet" />

    <!-- Ionicons -->
    <link href="~/lib/ionicons/ionicons.min.css" rel="stylesheet" />


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <script src="~/lib/jquery-1.10.2.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap.min.js"></script>
</head>
<body>
    <div class="login-box" style="margin: 0 auto 0 auto!important;">
        <div class="login-logo">
            <img src="~/images/egic.jpg" style="width:100%" />
            <div>
                <strong style="color: #725f58!important;">EGIC</strong>
                <small style="color: #f28b2f!important;">Projects Map</small>
            </div>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg text-center">
                <strong>Projects Map Application</strong>
                <br />
                <br />
                Login
            </p>

            <form asp-action="Login" asp-controller="Security" asp-route-returnurl="@Context.Request.Query["ReturnUrl"]" method="post">
                <p class=" alert-danger" ID="lblErrorMessage" visible="false">
                    <div asp-validation-summary="ModelOnly" class="message-error text-danger"></div>
                </p>
                <div class="form-group has-feedback">
                    <input asp-for="Username" class="form-control" autofocus="autofocus" placeholder="Username" />
                    <span asp-validation-for="Username"></span>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input asp-for="Password" class="form-control" placeholder="Password" />
                    <span asp-validation-for="Password"></span>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-4">
                        <input class="btn btn-success btn-block btn-flat" type="submit" value="Login" />
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-8">

                    </div>
                    <!-- /.col -->
                </div>
            </form>

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    @*
        <div class="col-xs-6">
            <div id="map" style="height:400px;width:100%"></div>
            <script>
                function initMap() {
                    var directionsService = new google.maps.DirectionsService;
                    var directionsRenderer = new google.maps.DirectionsRenderer;
                    var map = new google.maps.Map(document.getElementById('map'), {
                        zoom: 6,
                        center: { lat: 26.8206, lng: 30.8025 }
                    });
                    directionsRenderer.setMap(map);

                    document.getElementById('submit').addEventListener('click', function () {
                        calculateAndDisplayRoute(directionsService, directionsRenderer);
                    });
                }

                function calculateAndDisplayRoute(directionsService, directionsRenderer) {
                    var waypts = [];
                    var checkboxArray = document.getElementById('waypoints');
                    for (var i = 0; i < checkboxArray.length; i++) {
                        if (checkboxArray.options[i].selected) {
                            waypts.push({
                                location: checkboxArray[i].value,
                                stopover: true
                            });
                        }
                    }

                    directionsService.route({
                        origin: document.getElementById('start').value,
                        destination: document.getElementById('end').value,
                        waypoints: waypts,
                        optimizeWaypoints: true,
                        travelMode: 'DRIVING'
                    }, function (response, status) {
                        if (status === 'OK') {
                            directionsRenderer.setDirections(response);
                            var route = response.routes[0];
                            var summaryPanel = document.getElementById('directions-panel');
                            summaryPanel.innerHTML = '';
                            // For each route, display summary information.
                            for (var i = 0; i < route.legs.length; i++) {
                                var routeSegment = i + 1;
                                summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
                                    '</b><br>';
                                summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
                                summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                                summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                            }
                        } else {
                            window.alert('Directions request failed due to ' + status);
                        }
                    });
                }
            </script>
            <script async defer
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbf2inEldxLtJVulNzJQoSVqzL5J6aznI&callback=initMap">
            </script>
        </div>
        <div class="col-xs-6">
            <div id="map" style="height:400px;width:100%"></div>
            <script>
                var map;
                function initMap() {
                    map = new google.maps.Map(document.getElementById('map'), {
                        zoom: 2,
                        center: new google.maps.LatLng(2.8, -187.3),
                        mapTypeId: 'terrain'
                    });

                    // Create a <script> tag and set the USGS URL as the source.
                    var script = document.createElement('script');
                    // This example uses a local copy of the GeoJSON stored at
                    // http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojsonp
                    script.src = 'https://developers.google.com/maps/documentation/javascript/examples/json/earthquake_GeoJSONP.js';
                    document.getElementsByTagName('head')[0].appendChild(script);
                }

                // Loop through the results array and place a marker for each
                // set of coordinates.
                window.eqfeed_callback = function (results) {
                    for (var i = 0; i < results.features.length; i++) {
                        var coords = results.features[i].geometry.coordinates;
                        var latLng = new google.maps.LatLng(coords[1], coords[0]);
                        var marker = new google.maps.Marker({
                            position: latLng,
                            map: map
                        });
                    }
                }
            </script>
            <script async defer
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbf2inEldxLtJVulNzJQoSVqzL5J6aznI&callback=initMap">
            </script>
        </div>*@
</body>
</html>